apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume
spec:
  accessModes:
      - ReadWriteOnce
  capacity:
      storage: 1Gi
  hostPath: 
    path: /home/luc/github/kubernetes-trainning/tp4_volumes/data-volume
  
  # Déclaration d'un PV visible dans le cluster
  # Ceph, Cloud, stockage local