apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume
  labels: 
    type: local # Indicate the storage is on the node and not on the cloud
spec:
  accessModes:
      - ReadWriteOnce
  capacity:
      storage: 1Gi
  hostPath: 
    path: /data-volume # Check out if this directory is mounted into the Kubernetes container
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
