apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume
spec:
  accessModes:
      - ReadWriteOnce
  resources:
     requests:
       storage: 500Mi
  storageClassName: manual

  
  # PVCs are the resources used by pods