apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume
spec:
  accessModes:
      - ReadWriteOnce
  resources:
     requests:
       storage: 500Mi
  
  # Déclaration d'un PVC consommable par un pod